-- 0026_goalkeeper_exercises_seed.sql
-- 14 goalkeeper exercises (category football_goalkeeper).
-- Generated 2026-06-03 by scripts/generate-goalkeeper-seed.mjs via Groq openai/gpt-oss-120b.
-- Coaching fields use the JSONB shape introduced by migration 0011 and seeded
-- for football in migration 0013.
--
-- video_url is NULL for all rows: goalkeeper videos are sourced separately
-- (WebSearch + oEmbed) in a follow-up migration.
--
-- IMPORTANT: migration 0025 introduced the football_goalkeeper category
-- (profiles.is_goalkeeper flag) but did NOT extend exercises_category_check.
-- The constraint was last set by 0013 and allows the four football_* outfield
-- categories only. This migration extends it to include football_goalkeeper
-- BEFORE inserting, so the INSERT does not violate the check.

-- Extend category constraint to include football_goalkeeper
alter table public.exercises drop constraint if exists exercises_category_check;
alter table public.exercises add constraint exercises_category_check
  check (category in (
    'warmup', 'functional', 'team', 'balance',
    'flexibility', 'cardio', 'mobility', 'cooldown',
    'green', 'pair',
    'football_warmup', 'football_drill', 'football_trick', 'football_game',
    'football_goalkeeper'
  ));

insert into public.exercises (
  slug, category, difficulty,
  name, description,
  video_url, equipment, duration_minutes,
  min_age, max_age,
  why_matters, key_focus, pro_tip
) values
  (
    'gk-handling-basics',
    'football_goalkeeper',
    'low',
    '{"en":"W-Shape Catch Drill","pl":"Ćwiczenie chwytu W","it":"Esercizio presa a W","uk":"Вправи на захоплення В"}'::jsonb,
    '{"en":"Practice the basic catching technique using the W-shape hand position. This drill builds confidence in handling low and mid-range shots. 1. Stand in the central goal area with feet shoulder-width apart. 2. Hold the ball in both hands, forming a W with your thumbs and index fingers spread. 3. Have a partner toss the ball gently to your left and right at waist height. 4. Catch each ball using the W-shape, squeezing the ball into your chest. 5. Reset quickly and repeat for 5 minutes.","pl":"Ćwicz podstawową technikę parady z rękami w kształcie W. Ćwiczenie zwiększa pewność bramkarza przy chwytaniu niskich i średnich podań. 1. Stań w centralnej części bramki, stopy na szerokość barków. 2. Trzymaj piłkę obiema rękami, tworząc kształt W - kciuki i palce wskazujące rozstawione. 3. Partner delikatnie podaje piłkę po lewej i prawej stronie na wysokość pasa. 4. Chwyć piłkę w pozycji W, przyciskając ją do klatki piersiowej. 5. Szybko wróć do pozycji wyjściowej i powtarzaj przez 5 minut.","it":"Esercita la tecnica base della presa con le mani a forma di W. L''esercizio rinforza la sicurezza del portiere su tiri bassi e medi. 1. Posizionati al centro dell''area di porta con i piedi alla larghezza delle spalle. 2. Tieni la palla con entrambe le mani formando una W, con pollici e indice separati. 3. Un compagno lancia la palla delicatamente a sinistra e a destra all''altezza della vita. 4. Cattura la palla usando la presa a W, stringendola contro il petto. 5. Torna subito alla posizione di partenza e ripeti per 5 minuti.","uk":"Тренуйте базову техніку захоплення з руками у формі В. Вправа підвищує впевненість воротаря при низьких та середніх ударах. 1. Станьте в центр воріт, ноги на ширині плечей. 2. Тримаючи м''яч обома руками, сформуйте форму В - великий палець і вказівний розставлені. 3. Партнер м''яко підкидає м''яч ліворуч і праворуч на рівні талії. 4. Захоплюйте м''яч у позиції В, притискаючи його до грудей. 5. Швидко поверніться у вихідну позицію і повторюйте 5 хвилин."}'::jsonb,
    null,
    '{"ball"}'::text[],
    5,
    8,
    99,
    '{"en":"A solid catching foundation prevents rebounds and improves confidence under pressure. Goalkeepers like Manuel Neuer and Thibaut Courtois rely on a tight W-shape to secure low balls.","pl":"Podstawowa technika parady zmniejsza liczbę odbić i podnosi pewność bramkarza w trudnych sytuacjach. Łukasz Szczęśny i Wojciech Fabiański od lat wykorzystują ręce w kształcie W, aby pewnie łapać piłki przy ziemi.","it":"Una buona presa di base riduce i rimbalzi e aumenta la sicurezza del portiere. Gianluigi Buffon e Gianluigi Donnarumma hanno sempre mostrato una presa a W impeccabile per controllare i tiri bassi.","uk":"Сильна техніка захоплення зменшує кількість відскоків і підвищує впевненість воротаря під тиском. Олександр Лунин та Андрій П''ятов часто демонструють чисту захоплення у формі В, що допомагає їм контролювати низькі удари."}'::jsonb,
    '{"en":["Hand spread into W","Soft hands on impact","Quick reset","Chest control","Foot positioning"],"pl":["Ręce w kształcie W","Miękka chwyt","Szybka pozycja wyjściowa","Kontrola piłki przy klatce","Stopy na szerokość barków"],"it":["Mani a forma di W","Presenza morbida al contatto","Ripristino rapido","Controllo al petto","Posizione dei piedi corretta"],"uk":["Руки у формі В","М''яка захоплення","Швидке повернення","Контроль м''яча до грудей","Ноги на ширині плечей"]}'::jsonb,
    '{"en":"Think of your thumbs and index fingers as the top of a ''W'' that cradles the ball.","pl":"Wyobraź sobie, że kciuki i palce wskazujące tworzą górę litery W, w której piłka się ukrywa.","it":"Immagina i pollici e gli indici come la parte alta della ''W'' che avvolge la palla.","uk":"Уявіть, що великий палець і вказівний створюють верхню частину «В», яка обіймає м''яч."}'::jsonb
  ),
  (
    'gk-warmup-handling',
    'football_goalkeeper',
    'low',
    '{"en":"Soft Catch Warmup","pl":"Rozgrzewka miękkich par","it":"Riscaldamento prese morbide","uk":"Розігрів м''яких сейвів"}'::jsonb,
    '{"en":"A quick warm-up that combines light footwork with soft catches to activate the hands and improve reaction speed. 1. Place three cones in a triangle about 5 meters apart.\n2. Start at the base cone, jog to the next cone, and perform a soft catch from a partner''s gentle toss.\n3. Return to the start, repeat the pattern moving clockwise, focusing on a balanced stance and soft hands.\n4. After each circuit, increase the distance slightly while keeping the toss light.","pl":"Szybka rozgrzewka łącząca lekkie wyjścia i miękkie pary, aby rozbudzić ręce i poprawić szybkość reakcji. 1. Ustaw trzy pachołki w trójkącie oddalonym o ok. 5 m.\n2. Rozpocznij od jednego pachołka, przebiegnij do kolejnego i złap miękką piłkę podawaną przez partnera.\n3. Wróć do startu, powtórz schemat w kierunku zgodnym z ruchem wskazówek zegara, zachowując stabilną pozycję i miękką rękę.\n4. Po każdym obiegu zwiększ nieco odległość, utrzymując lekki podanie.","it":"Un riscaldamento veloce che unisce movimenti leggeri del portiere a prese morbide, attivando le mani e la prontezza. 1. Sistema tre coni a forma di triangolo a circa 5 metri l''uno dall''altro.\n2. Parti dal cono di base, corri al cono successivo e prendi una palla leggera lanciata dal compagno.\n3. Torna al punto di partenza e ripeti il percorso in senso orario, mantenendo una posizione equilibrata e una presa morbida.\n4. Dopo ogni giro allunga leggermente la distanza mantenendo il lancio delicato.","uk":"Швидка розминка, що поєднує легкі кроки з м''якими сейвами, активізує руки та підвищує швидкість реакції. 1. Розставте три конуси у вигляді трикутника на відстані приблизно 5 м один від одного.\n2. Починаючи з одного конуса, пробіжіть до наступного і зловіть легкий м''який м''яч, який підкидає партнер.\n3. Поверніться до старту, повторюйте рух за годинниковою стрілкою, тримаючи збалансовану позицію та м''які руки.\n4. Після кожного кола трохи збільшуйте відстань, залишаючи підкиди легкими."}'::jsonb,
    null,
    '{"ball"}'::text[],
    4,
    8,
    99,
    '{"en":"Handling soft catches builds hand-eye coordination and prepares the keeper for rapid, high-intensity saves. Keepers like Manuel Neuer and Thibaut Courtois credit consistent warm-ups for their reflexes.","pl":"Trening miękkich par rozwija koordynację ręka-oko i przygotowuje bramkarza do szybkich, intensywnych interwencji. Szczególnie Janusz Szczęsny i Łukasz Fabiański podkreślają, że regularna rozgrzewka wpływa na ich refleks.","it":"Le prese morbide migliorano la coordinazione mano-occhio e preparano il portiere a parate rapide. Gianluigi Buffon e Gianluigi Donnarumma hanno sempre sottolineato l''importanza del riscaldamento per i riflessi.","uk":"М''які сейви розвивають координацію «рука-око» і готують воротаря до швидких, інтенсивних відбиттів. Лунін та Пятов часто наголошують, що регулярна розминка підвищує їх реакцію."}'::jsonb,
    '{"en":["Soft hand positioning","Balanced footwork","Quick reaction","Consistent toss height"],"pl":["Miękka pozycja rąk","Zrównoważone wyjścia","Szybka reakcja","Stała wysokość podania"],"it":["Morbida posizione delle mani","Movimenti equilibrati","Reazione rapida","Altezza costante del lancio"],"uk":["М''яка позиція рук","Збалансовані кроки","Швидка реакція","Постійна висота підкиду"]}'::jsonb,
    '{"en":"Treat every soft catch as if it were a real shot - the tighter the grip, the sharper the reflexes.","pl":"Traktuj każdą miękką parę jak prawdziwą strzał - mocniejszy chwyt zwiększa refleks.","it":"Considera ogni presa morbida come un tiro reale: una presa più stretta affina i riflessi.","uk":"Кожен м''який сейв сприймай як справжній удар - міцний захват підвищує реакцію."}'::jsonb
  ),
  (
    'gk-footwork-set-position',
    'football_goalkeeper',
    'low',
    '{"en":"Set Position Footwork","pl":"Praca nad pozycją","it":"Movimenti di posizione","uk":"Вправи на позицію"}'::jsonb,
    '{"en":"Practice quick, small steps to stay in the optimal ready position. 1. Stand in the centre of the goal line with feet shoulder-width apart. 2. On the coach''s signal, take a small step forward with the right foot, then the left, staying low. 3. Return to the centre with mirrored steps, keeping weight balanced. 4. Repeat for 30 seconds, focusing on smooth transitions.","pl":"Ćwicz małe kroki, aby bramkarz zawsze był w prawidłowej pozycji gotowości. 1. Stań w centrum bramki, stopy na szerokość barków. 2. Na sygnał trenera wykonaj mały krok w prawo, potem w lewo, pozostając w niskiej pozycji. 3. Wróć do środka odwrotnymi krokami, utrzymując równowagę. 4. Powtarzaj przez 30 sekund, koncentrując się na płynnych przejściach.","it":"Esegui piccoli passi per mantenere il portiere nella posizione pronta ideale. 1. Posizionati al centro della linea di porta con i piedi alla larghezza delle spalle. 2. Al segnale dell''allenatore, fai un piccolo passo in avanti con il piede destro, poi con il sinistro, mantenendo il corpo basso. 3. Torna al centro con passi speculari, tenendo il peso equilibrato. 4. Ripeti per 30 secondi, concentrandoti su transizioni fluide.","uk":"Тренуйте швидкі короткі кроки, щоб воротар завжди був у правильній позиції готовності. 1. Станьте в центр воріт, ноги на ширину плеч. 2. По сигналу тренера зробіть короткий крок правою ногою, потім лівою, залишаючись низько. 3. Поверніться в центр зворотними кроками, тримаючи баланс. 4. Повторюйте 30 секунд, зосереджуючись на плавних переходах."}'::jsonb,
    null,
    '{"ball"}'::text[],
    5,
    8,
    99,
    '{"en":"A solid set position lets the goalkeeper react faster to shots and crosses. Goalkeepers like Manuel Neuer and Thibaut Courtois build their reputation on impeccable footwork.","pl":"Stabilna pozycja pozwala bramkarzowi szybciej reagować na strzały i dośrodkowania. Łukasz Szczęsny i Wojciech Fabiański są przykładem, jak precyzyjne kroki zwiększają pewność w bramce.","it":"Una buona posizione di partenza consente al portiere di reagire rapidamente a tiri e cross. Gianluigi Buffon e Gianluigi Donnarumma dimostrano come il lavoro sui piedi sia fondamentale.","uk":"Стабільна позиція дозволяє воротарю швидше реагувати на удари та навіси. Лунін і Пятов показали, що впевнені кроки підвищують ефективність сейвів."}'::jsonb,
    '{"en":["Feet shoulder-width apart","Small, quick steps","Low center of gravity","Balanced weight distribution"],"pl":["Stopy na szerokość barków","Małe, szybkie kroki","Niska pozycja ciała","Równomierny rozkład wagi"],"it":["Piedi alla larghezza delle spalle","Passi piccoli e rapidi","Bassa posizione del corpo","Distribuzione equilibrata del peso"],"uk":["Ноги на ширину плеч","Короткі швидкі кроки","Низька позиція тіла","Рівномірний розподіл ваги"]}'::jsonb,
    '{"en":"Think of your feet as the first line of defense; keep them moving.","pl":"Pamiętaj, że nogi to pierwsza linia obrony - nie przestawaj ich ruszać.","it":"Le gambe sono la prima linea di difesa: mantienile sempre in movimento.","uk":"Ноги - це перша лінія захисту, тримайте їх у постійному русі."}'::jsonb
  ),
  (
    'gk-low-dive-save',
    'football_goalkeeper',
    'mid',
    '{"en":"Low Dive Save","pl":"Niska Parada Skokowa","it":"Parata Bassa in Tuffo","uk":"Низьке занурення у сейв"}'::jsonb,
    '{"en":"The keeper practices low diving saves to both sides, improving reaction and reach when the ball is at ground level. Focus on staying low and driving the hips into the dive. 1. Place the ball a few meters in front of the goal line. 2. From a ready stance, push off the right foot and dive low to the left, extending arms to meet the ball. 3. Reset quickly, then repeat the dive to the right using the left foot. 4. Perform 8 repetitions per side, focusing on a smooth landing.","pl":"Bramkarz ćwiczy niskie parady w lewo i w prawo, rozwijając reakcję i zasięg przy piłce przy ziemi. Skup się na niskiej pozycji i dynamicznym wyjściu. 1. Ustaw piłkę kilka metrów przed linią bramki. 2. Z gotowej pozycji wypchnij prawą nogą i wykonaj niskie wyjście w lewo, wyciągając ręce do piłki. 3. Szybko wróć do pozycji wyjściowej i powtórz skok w prawo, wypychając lewą nogą. 4. Wykonaj po 8 powtórzeń na każdą stronę, koncentrując się na płynnym lądowaniu.","it":"Il portiere esegue parate basse a sinistra e a destra, migliorando reazione e copertura quando il pallone è a terra. Mantieni una posizione bassa e spingi i fianchi nel tuffo. 1. Posiziona la palla a pochi metri dalla linea di porta. 2. Dalla posizione pronta, spingi con il piede destro e tuffati in basso a sinistra, allungando le braccia verso la palla. 3. Ripristina rapidamente, poi ripeti il tuffo a destra usando il piede sinistro. 4. Esegui 8 ripetizioni per lato, concentrandoti su un atterraggio fluido.","uk":"Воротар практикує низькі занурення вліво та вправо, підвищуючи реакцію та охоплення при м''ячі на підлозі. Зосередьтеся на низькій позиції та швидкому відштовхуванні. 1. Поставте м''яч за кілька метрів перед лінією воріт. 2. З готової позиції відштовхніться правою ногою та зануртесь низько вліво, простягнувши руки до м''яча. 3. Швидко поверніться у вихідну позицію і повторіть занурення вправо, використовуючи ліву ногу. 4. Виконайте по 8 повторень на кожну сторону, зосереджуючись на плавному приземленні."}'::jsonb,
    null,
    '{"ball"}'::text[],
    8,
    8,
    99,
    '{"en":"Low dives are essential for stopping shots aimed at the bottom corners, where many goals are conceded. Goalkeepers like Manuel Neuer and Thibaut Courtois use this technique to dominate the box.","pl":"Niskie parady są kluczowe przy strzałach w dolne rogi, które najczęściej prowadzą do bramek. Bramkarze jak Wojciech Szczęsny i Łukasz Fabiański regularnie wykorzystują tę technikę, aby utrzymać czyste konto.","it":"Le parate basse sono fondamentali contro i tiri verso gli angoli inferiori, dove si segnano la maggior parte dei gol. Portieri come Gianluigi Buffon e Gianluigi Donnarumma le eseguono con grande efficacia.","uk":"Низькі занурення важливі для зупинки ударів у нижні кути, звідки часто забиваються голи. Голкіпери як Лунін і Пятов часто застосовують цю техніку, щоб контролювати штрафну зону."}'::jsonb,
    '{"en":["low center of gravity","quick push-off","balanced landing","eyes on ball"],"pl":["niska pozycja ciała","szybki wypchnięcie","zrównoważone lądowanie","oczy na piłce"],"it":["bassa posizione del corpo","spinta rapida","atterraggio equilibrato","sguardo sulla palla"],"uk":["низка позиція тіла","швидкий відштовх","збалансоване приземлення","очі на м''ячі"]}'::jsonb,
    '{"en":"Drive your hips into the dive; a powerful push creates a longer reach.","pl":"Wypchnij biodra mocno w turlanie; silny odrzut zwiększa zasięg.","it":"Spingi i fianchi nel tuffo; una spinta potente allunga la portata.","uk":"Відштовхуйте таз у зануренні; потужний відштовх збільшує охоплення."}'::jsonb
  ),
  (
    'gk-high-catch',
    'football_goalkeeper',
    'mid',
    '{"en":"High Ball Claim","pl":"Chwyt wysokich piłek","it":"Cattura palloni alti","uk":"Ловля високих м''ячів"}'::jsonb,
    '{"en":"Practice catching high balls safely and timing your jump to dominate the aerial area. 1. Place the ball on a tee or have a partner toss it high toward the goal area. 2. Start in your set position, feet shoulder-width apart. 3. As the ball descends, explode upward, keeping eyes on the ball. 4. Catch the ball with both hands, securing it to your chest. 5. Reset and repeat, varying the height and angle.","pl":"Ćwicz bezpieczne łapanie wysokich piłek i precyzyjne wyjście w powietrzu. 1. Ustaw piłkę na podwyższeniu lub poproś partnera o wysokie podania w stronę bramki. 2. Zacznij w podstawowej pozycji, stopy na szerokość barków. 3. Gdy piłka spada, wykonaj dynamiczny skok, patrząc w jej kierunku. 4. Złap piłkę obiema rękami, przyciskając ją do klatki piersiowej. 5. Powróć do pozycji wyjściowej i powtórz, zmieniając wysokość i kąt podania.","it":"Allena la presa di palloni alti e il tempismo del salto per dominare l''area aerea. 1. Posiziona la palla su un supporto o chiedi a un compagno di lanciare palloni alti verso la porta. 2. Parti dalla posizione di base, piedi alla larghezza delle spalle. 3. Quando la palla scende, esegui un salto esplosivo mantenendo gli occhi sulla palla. 4. Cattura la palla con entrambe le mani, stringendola al petto. 5. Torna alla posizione di partenza e ripeti, variando altezza e angolo.","uk":"Тренуйте безпечний захват високих м''ячів і правильний час підйому. 1. Розмістіть м''яч на підставці або попросіть партнера підкинути високий м''яч у напрямку воріт. 2. Почніть у базовій позиції, ноги на ширині плечей. 3. Коли м''яч спускається, різко підстрибніть, тримаючи погляд на м''ячі. 4. Зробіть сейв обома руками, притискаючи м''яч до грудей. 5. Поверніться у вихідну позицію і повторіть, змінюючи висоту та кут підкидання."}'::jsonb,
    null,
    '{"ball"}'::text[],
    6,
    8,
    99,
    '{"en":"Claiming high balls prevents dangerous headers and gives your team control. Goalkeepers like Manuel Neuer and Alisson Becker show how confidence in the air can change a match.","pl":"Skuteczny chwyt wysoko chroni przed niebezpiecznymi główkami i daje bramkarzowi kontrolę. Szczęsny i Fabiański pokazują, jak pewność w powietrzu wpływa na cały zespół.","it":"Una buona parata alta elimina i pericoli di colpi di testa e dà al portiere il controllo del gioco. Buffon e Donnarumma dimostrano come la sicurezza aerea possa cambiare le partite.","uk":"Вміння ловити високі м''ячі запобігає небезпечним головам і дає воротарю контроль над грою. Лунін і Пятов демонструють, як впевненість у повітрі підвищує результат команди."}'::jsonb,
    '{"en":["Jump timing","Hand positioning","Body balance","Eyes on the ball"],"pl":["Timing skoku","Ustawienie rąk","Balans ciała","Patrzenie na piłkę"],"it":["Tempismo salto","Posizione delle mani","Equilibrio corporeo","Occhi sulla palla"],"uk":["Час підйому","Позиція рук","Баланс тіла","Погляд на м''яч"]}'::jsonb,
    '{"en":"Stay on the balls of your feet so you can explode upward instantly.","pl":"Trzymaj ciężar na palcach, aby móc natychmiast wystrzelić w górę.","it":"Mantieni il peso sui piedi per saltare più rapidamente.","uk":"Тримайте вагу на передніх частинах стоп, щоб швидко підскочити."}'::jsonb
  ),
  (
    'gk-shot-stopping-reactions',
    'football_goalkeeper',
    'mid',
    '{"en":"Close-Range Reaction Saves","pl":"Reakcje przy bliskich strzałach","it":"Parate a corto raggio","uk":"Реакції при близьких ударах"}'::jsonb,
    '{"en":"Goalkeepers practice stopping fast shots from the edge of the box to sharpen reflexes. The drill emphasizes quick set‑up and explosive movement. 1. Place the goalkeeper on the edge of the penalty area facing the shooter. 2. The shooter fires a series of quick, low shots from 5‑10 meters. 3. The keeper must set a balanced stance, react instantly, and make a clean catch or deflection. 4. Reset after each attempt and repeat for 8 minutes.","pl":"Bramkarz trenuje parady przy bliskich strzałach, aby poprawić refleks. Ćwiczenie wymaga szybkiego ustawienia i natychmiastowego wyjścia. 1. Ustaw bramkarza na krawędzi pola karnego, twarzą do strzelca. 2. Strzelec oddaje serię szybkich, niskich strzałów z odległości 5‑10 m. 3. Bramkarz przyjmuje stabilną pozycję, reaguje natychmiast i wykonuje czystą parę lub odbiór. 4. Po każdym strzale resetuj pozycję i kontynuuj przez 8 minut.","it":"Il portiere si allena a parare tiri ravvicinati per migliorare i riflessi. L''esercizio richiede una posizione pronta e un''uscita esplosiva. 1. Posiziona il portiere sul bordo dell''area di rigore, rivolto verso il tiratore. 2. Il tiratore effettua una serie di tiri rapidi e bassi da 5‑10 m. 3. Il portiere assume una posizione equilibrata, reagisce subito e realizza una presa pulita o una parata. 4. Dopo ogni tiro ripristina la posizione e continua per 8 minuti.","uk":"Воротар практикує сейви з близької відстані, щоб підвищити реакцію. Вправа вимагає швидкої позиції та миттєвого виходу. 1. Розташувати воротаря на межі штрафного майданчика, обличчям до гравця. 2. Гравець виконує швидкі низькі удари з відстані 5‑10 м. 3. Воротар приймає збалансовану позицію, миттєво реагує і робить чистий сейв або відбиття. 4. Після кожного удару відновлює позицію і продовжує протягом 8 хвилин."}'::jsonb,
    null,
    '{"ball"}'::text[],
    8,
    8,
    99,
    '{"en":"Quick reactions are essential for denying close-range chances, a skill mastered by Manuel Neuer and Thibaut Courtois. Practicing this drill builds the split‑second decision‑making needed in real games.","pl":"Szybka reakcja przy bliskich strzałach to podstawa, którą doskonalił Wojciech Szczęsny oraz Łukasz Fabiański. Regularny trening rozwija refleks i pewność w parowaniu w ciasnych sytuacjach.","it":"Reazioni fulminee sono fondamentali, come dimostrano Gianluigi Buffon e Gianluigi Donnarumma. Questo esercizio affina la capacità di parare tiri ravvicinati nei momenti decisivi.","uk":"Швидка реакція на близькі удари - ключова якість, яку демонструють Лунін і Пятов. Тренування розвиває миттєве прийняття рішень і впевненість у сейвах під тиском."}'::jsonb,
    '{"en":["Balanced stance","Explosive first step","Soft hands for catching","Quick recovery"],"pl":["Stabilna pozycja","Wybuchowy wyjscie","Czysta parada","Szybka pozycja po wyrzucie"],"it":["Posizione equilibrata","Uscita esplosiva","Presenza di mani morbide","Recupero rapido"],"uk":["Збалансована позиція","Вибуховий вихід","М''які руки для сейву","Швидке відновлення позиції"]}'::jsonb,
    '{"en":"Treat every close shot as a sudden sprint - your first move decides the outcome.","pl":"Traktuj każdy bliski strzał jak nagły sprint - pierwszy ruch decyduje.","it":"Considera ogni tiro ravvicinato come uno sprint improvviso - il primo movimento è decisivo.","uk":"Сприймайте кожен близький удар як спринт - перший рух визначає результат."}'::jsonb
  ),
  (
    'gk-reflex-wall-rebound',
    'football_goalkeeper',
    'mid',
    '{"en":"Wall Rebound Reflex","pl":"Reakcja przy ścianie","it":"Riflesso muro rimbalzo","uk":"Рефлекс від стіни"}'::jsonb,
    '{"en":"A quick drill to sharpen close-range reflexes using a wall or rebounder. The ball returns instantly, forcing the keeper to react fast. 1. Stand 2-3 m from a solid wall with your knees slightly bent. 2. Position yourself in a ready stance, hands low and elbows out. 3. Toss the ball against the wall and prepare to catch or deflect the rebound. 4. React as quickly as possible, focusing on hand placement and foot balance.","pl":"Ćwiczenie rozwija szybkie reakcje bramkarza przy bliskim strzale z wykorzystaniem ściany lub reboundera. Piłka wraca natychmiast, wymuszając błyskawiczną parę. 1. Stań 2-3 m od solidnej ściany, lekko ugięte kolana. 2. Przyjmij gotową pozycję, ręce nisko, łokcie na zewnątrz. 3. Rzuć piłkę w ścianę i przygotuj się do parady lub wykopu po odbiciu. 4. Reaguj jak najszybciej, zwracając uwagę na chwyt i stabilność nóg.","it":"Esercizio veloce per migliorare i riflessi a distanza ravvicinata usando una parete o un rimbalzo. La palla ritorna subito, costringendo il portiere a reagire in fretta. 1. Posizionati a 2-3 m dalla parete con le ginocchia leggermente piegate. 2. Assumi una postura pronta, mani basse ed i gomiti aperti. 3. Lancia la palla contro la parete e preparati a effettuare una parata o un rinvio al rimbalzo. 4. Reagisci il più velocemente possibile, curando la presa e l''equilibrio dei piedi.","uk":"Швидке вправляння для покращення рефлексу воротаря на близькі удари за допомогою стіни або рикошету. М''яч миттєво повертається, змушуючи воротаря реагувати швидко. 1. Станьте 2-3 м від стіни, коліна трохи зігнуті. 2. Прийміть готову позицію, руки низько, лікті розведені. 3. Киньте м''яч у стіну і готуйтеся до сейву або відкидання після відскоку. 4. Реагуйте якомога швидше, контролюючи підхват і баланс ніг."}'::jsonb,
    null,
    '{"ball"}'::text[],
    6,
    8,
    99,
    '{"en":"Fast reflexes are essential for stopping close-range shots and deflections. Goalkeepers like Manuel Neuer and Alisson Becker built their reputations on lightning‑quick reactions.","pl":"Szybka reakcja jest kluczowa przy bliskich strzałach i odbiciach. Bramkarze tacy jak Wojciech Szczęsny i Łukasz Fabiański słyną z błyskawicznych par.","it":"I riflessi rapidi sono fondamentali per fermare tiri ravvicinati e deviazioni. Portieri come Gianluigi Buffon e Gianluigi Donnarumma hanno mostrato parate fulminee durante le loro carriere.","uk":"Швидкі рефлекси необхідні для зупинки близьких ударів і відхилень. Воротарі такі як Владислав Лунін і Андрій Пятов часто демонстрували блискавичні сейви."}'::jsonb,
    '{"en":["Hand placement","Footwork and balance","Reaction time","Body tension control"],"pl":["Pozycja rąk","Praca nóg i równowaga","Czas reakcji","Kontrola napięcia ciała"],"it":["Posizione delle mani","Lavoro di piedi ed equilibrio","Tempo di reazione","Controllo della tensione corporea"],"uk":["Розташування рук","Робота ніг та баланс","Час реакції","Контроль напруги тіла"]}'::jsonb,
    '{"en":"Keep your eyes on the ball until it leaves the wall to minimize blind spots.","pl":"Patrz na piłkę aż do momentu odbicia, aby uniknąć ślepych stref.","it":"Mantieni lo sguardo sulla palla fino al rimbalzo per ridurre le zone cieche.","uk":"Слідкуйте за м''ячем до відскоку, щоб уникнути сліпих зон."}'::jsonb
  ),
  (
    'gk-positioning-angles',
    'football_goalkeeper',
    'mid',
    '{"en":"Angle Narrowing Drill","pl":"Ćwiczenie wąskich kątów","it":"Esercizio riduzione angolo","uk":"Вправи зі звуження кута"}'::jsonb,
    '{"en":"A short drill that teaches the keeper to cut down shooting angles from the edge of the box. 1. Place the ball on the 6-yard line. 2. The goalkeeper starts on the goal line in the central position. 3. A coach or partner rolls a ball toward the near post at a moderate pace. 4. The keeper steps out, narrows the angle, and makes a controlled catch or parry. 5. Reset and repeat from the opposite side.","pl":"Krótka seria, w której bramkarz uczy się zmniejszać kąt strzału z obrzeży pola karnego. 1. Ustaw piłkę na linii 6-metrów. 2. Bramkarz zaczyna w centralnej pozycji na linii bramki. 3. Trener podaje piłkę w stronę najbliższego słupka. 4. Bramkarz wykonuje wyjście, zmniejsza kąt i wykonuje kontrolny chwyt lub parę. 5. Reset i powtórz z drugiej strony.","it":"Un breve esercizio per insegnare al portiere a ridurre l''angolo di tiro dal limite dell''area. 1. Posiziona la palla sulla linea dei 6 metri. 2. Il portiere parte al centro della linea di porta. 3. Un compagno lancia la palla verso il palo più vicino. 4. Il portiere esce, accorcia l''angolo e afferra o para la palla. 5. Ripeti dall''altro lato.","uk":"Коротка вправа, яка навчає воротаря скорочувати кут удару з краю штрафної площі. 1. Розмістіть м''яч на лінії 6-метрів. 2. Голкіпер стоїть у центрі лінії воріт. 3. Партнер підкидає м''яч до найближчого стовпа. 4. Голкіпер робить вихід, звужує кут і ловить або відбиває м''яч. 5. Поверніть м''яч і повторіть з іншого боку."}'::jsonb,
    null,
    '{"ball"}'::text[],
    6,
    8,
    99,
    '{"en":"Narrowing the angle reduces the target area and forces shooters into low‑percentage zones. Goalkeepers like Alisson, Manuel Neuer and Thibaut Courtois use this principle to dominate the box.","pl":"Zmniejszanie kąta ogranicza pole strzału i zmusza napastników do trudniejszych sytuacji. Bramkarze tacy jak Wojciech Szczęsny i Łukasz Fabiański stosują tę zasadę w meczach.","it":"Ridurre l''angolo limita le opzioni del tiratore e aumenta le probabilità di parata. Portieri come Gianluigi Buffon e Gianluigi Donnarumma usano costantemente questo principio.","uk":"Звуження кута зменшує площу цілі і змушує гравця робити менш вдалий удар. Воротарі як Лунін і Пятов часто застосовують цю техніку в матчах."}'::jsonb,
    '{"en":["Starting position","Angle reduction","Footwork","Hand placement","Recovery"],"pl":["Pozycja wyjściowa","Redukcja kąta","Przemieszczanie nóg","Chwyt","Szybka odbiór"],"it":["Posizione di partenza","Riduzione dell''angolo","Movimento dei piedi","Presenza della mano","Recupero rapido"],"uk":["Стартова позиція","Звуження кута","Рухи ніг","Позиція рук","Швидке відновлення"]}'::jsonb,
    '{"en":"Always keep your hips square to the line of the shot.","pl":"Utrzymuj biodra skierowane w stronę linii strzału.","it":"Mantieni i fianchi allineati con la direzione del tiro.","uk":"Тримайте таз паралельно до лінії удару."}'::jsonb
  ),
  (
    'gk-1v1-closing-down',
    'football_goalkeeper',
    'high',
    '{"en":"Close Down 1v1","pl":"Zamknięcie 1v1","it":"Chiudi 1v1","uk":"Закриття 1v1"}'::jsonb,
    '{"en":"The keeper learns to cut down the angle and force the attacker into a weak side. 1. Place the ball on the edge of the penalty area. 2. The attacker starts 5 meters out and dribbles toward the goal. 3. As the attacker approaches, the keeper steps out, narrows the angle and closes down the space. 4. The keeper aims to make a low parry or catch the ball. 5. Reset and repeat with the attacker alternating sides.","pl":"Bramkarz uczy się zmniejszyć kąt i zmusić napastnika do słabszej strony. 1. Ustaw piłkę na krawędzi pola karnego. 2. Napastnik zaczyna 5 metrów od bramki i podbiega z piłką. 3. Gdy napastnik zbliża się, bramkarz wychodzi, zmniejsza kąt i zamyka przestrzeń. 4. Bramkarz stara się wykonać niską parę lub chwycić piłkę. 5. Resetuj i powtarzaj, zmieniając stronę napastnika.","it":"Il portiere impara a ridurre l''angolo e costringere l''attaccante al lato più debole. 1. Posiziona la palla sul bordo dell''area di rigore. 2. L''attaccante parte a 5 metri dalla porta e dribbla verso il goal. 3. Quando l''attaccante si avvicina, il portiere esce, riduce l''angolo e chiude lo spazio. 4. Il portiere mira a una parata bassa o a una presa della palla. 5. Ripristina e ripeti alternando i lati dell''attaccante.","uk":"Голкіпер вчиться скорочувати кут і змушувати нападника грати на слабшій стороні. 1. Поставте м''яч на край штрафного майданчика. 2. Нападник стартує за 5 метрів і веде м''яч до воріт. 3. Коли нападник підходить, воротар робить вихід, звужує кут і закриває простір. 4. Воротар намагається виконати низький сейв або відбиття м''яча. 5. Скидайте і повторюйте, змінюючи сторону нападника."}'::jsonb,
    null,
    '{"ball"}'::text[],
    8,
    8,
    99,
    '{"en":"Closing down quickly limits the shooter''s options and creates a higher chance of a save. Goalkeepers like Manuel Neuer and Thibaut Courtois excel at this aggressive positioning.","pl":"Szybkie zamknięcie zmniejsza wybór strzelca i zwiększa szansę na udaną parę. Bramkarze jak Wojciech Szczęsny i Łukasz Fabiański są znani z agresywnego wyjścia i skutecznych par.","it":"Ridurre rapidamente lo spazio costringe il tiratore a decisioni sbagliate e aumenta le probabilità di parata. Portieri come Gianluigi Buffon e Gianluigi Donnarumma mostrano eccellenza in questo aspetto.","uk":"Швидке закриття простору обмежує варіанти удару і підвищує шанс на сейв. Воротарі як Лунін і П''ятов демонструють майстерність у цьому."}'::jsonb,
    '{"en":["Angle reduction","Quick footwork","Low body position","Aggressive closing","Secure catch or parry"],"pl":["Zmniejszanie kąta","Szybki ruch nóg","Niska pozycja ciała","Agresywne wyjście","Bezpieczna parada lub chwyt"],"it":["Riduzione angolo","Movimento rapido dei piedi","Posizione bassa","Uscita aggressiva","Parata o presa sicura"],"uk":["Зменшення кута","Швидка робота ніг","Низька позиція","Агресивний вихід","Безпечний сейв або відбиття"]}'::jsonb,
    '{"en":"Stay on the balls of your feet so you can explode toward the shooter.","pl":"Trzymaj się na palcach, by móc natychmiastowy wyjść w stronę napastnika.","it":"Mantieni il peso sulle punte per scattare subito verso il tiratore.","uk":"Тримайте вагу на носках, щоб миттєво вийти назустріч нападнику."}'::jsonb
  ),
  (
    'gk-cross-claiming',
    'football_goalkeeper',
    'high',
    '{"en":"Cross Claim Drill","pl":"Zgarnianie dośrodkowań","it":"Rivendicazione cross","uk":"Відбір кросів"}'::jsonb,
    '{"en":"Goalkeeper practices timing jumps to claim high crosses, choosing between a punch or a secure catch. 1. Set up three cones 5 meters apart along the goal line. 2. Coach or teammate delivers high crosses from the wing at varying heights. 3. Goalkeeper starts in goal line position, times the jump to meet the ball at its apex. 4. Decide to catch (secure grip) or punch (strong swing) based on ball control, then reset.","pl":"Bramkarz trenuje timing wyjścia przy dośrodkowaniach, decydując o parady - chwyt lub wykop. 1. Ustaw trzy pachołki w odległości 5 metrów wzdłuż linii bramki. 2. Trener lub kolega podaje wysokie dośrodkowania z bocznej linii na różne wysokości. 3. Bramkarz zaczyna w pozycji na linii bramki, wyczuwa timing wyjścia, aby spotkać piłkę w szczycie jej lotu. 4. Wybierz chwyt (pewny chwyt) lub wykop (mocny swing) w zależności od kontroli piłki, po czym resetuj pozycję.","it":"Il portiere allena il tempismo per uscire su cross, scegliendo tra una presa sicura o un rinvio. 1. Posiziona tre coni a 5 metri l''uno dall''altro lungo la linea di porta. 2. L''allenatore o un compagno lancia cross alti dalla fascia a diverse altezze. 3. Il portiere parte dalla posizione di porta, cronometrando il salto per incontrare la palla al suo apice. 4. Decidi di prendere (presa sicura) o di rinviare (colpo forte) a seconda del controllo, poi ripristina la posizione.","uk":"Голкіпер відпрацьовує таймінг стрибка на кроси, вирішуючи чи робити сейв чи відбиття. 1. Розставте три конуси на відстані 5 метрів один від одного вздовж лінії воріт. 2. Тренер або товариш подає високі кроси з флангу на різних висотах. 3. Голкіпер починає у позиції на лінії воріт, розраховує таймінг стрибка, щоб зустріти м''яч у його вершині. 4. Вирішіть, чи робити сейв (надійний захват) чи відбиття (сильний удар) залежно від контролю, після чого поверніться у вихідну позицію."}'::jsonb,
    null,
    '{"ball"}'::text[],
    8,
    8,
    99,
    '{"en":"Timing cross claims prevents dangerous second‑ball chances and builds confidence. Keepers like Manuel Neuer and Thibaut Courtois are known for decisive punches and safe catches under pressure.","pl":"Dobre timing wyjścia przy dośrodkowaniach eliminuje niebezpieczne sytuacje i podnosi pewność bramkarza. Szczęsny i Fabiański słyną z pewnych chwytań i skutecznych wykopów w kluczowych momentach.","it":"Un tempismo corretto nelle rivendicazioni dei cross elimina pericoli e aumenta la fiducia del portiere. Buffon e Donnarumma sono esempi di eccellenza nei rinvii decisivi e nelle prese sicure.","uk":"Точний таймінг відбору кросів знижує ризик других шансів і підвищує впевненість воротаря. Лунін і Пятов демонструють майстерність у швидких сейвах і точних відбиттях."}'::jsonb,
    '{"en":["Jump timing","Positioning under the ball","Decision: punch vs catch","Hand placement","Recovery speed"],"pl":["Timing wyjścia","Pozycja pod piłką","Decyzja: chwyt czy wykop","Ustawienie rąk","Szybkość powrotu"],"it":["Tempismo salto","Posizione sotto palla","Scelta: presa o rinvio","Posizionamento mani","Recupero rapido"],"uk":["Таймінг стрибка","Позиція під м''ячем","Вибір: сейв чи відбиття","Розташування рук","Швидкість повернення"]}'::jsonb,
    '{"en":"If the ball is above your waist, punch; if it''s within reach, catch to keep possession.","pl":"Jeśli piłka jest powyżej pasa, lepszy wykop; w zasięgu - pewny chwyt.","it":"Se la palla è sopra la vita, opta per il rinvio; se è alla tua altezza, scegli la presa.","uk":"Якщо м''яч вище талії - відбивай, якщо в досяжності - ловись."}'::jsonb
  ),
  (
    'gk-distribution-throwing',
    'football_goalkeeper',
    'low',
    '{"en":"Throwing Accuracy Drill","pl":"Ćwiczenie precyzyjnego wyrzutu","it":"Esercizio di precisione nel lancio","uk":"Тренування точного кидка"}'::jsonb,
    '{"en":"Goalkeepers practice rolling the ball and javelin throws to improve distribution accuracy. 1. Set up two cones 5 meters apart. 2. Start in the central position, receive a pass, and roll the ball to the far cone. 3. After the roll, pick up the ball and perform a javelin throw back to the start line, aiming for the target zone. 4. Reset and repeat for 10 repetitions on each side.","pl":"Bramkarz ćwiczy podania rolkowe i wyrzuty javelin, aby zwiększyć precyzję rozgrywania piłki. 1. Ustaw dwa pachołki w odległości 5 metrów. 2. Bramkarz zaczyna w środku, przyjmuje piłkę i wykonuje rolkę do dalszego pachołka. 3. Po roli podnosi piłkę i wykonuje wyrzut javelin w kierunku linii startu, celując w wyznaczoną strefę. 4. Resetuj i powtórz 10 razy po każdej stronie.","it":"Il portiere allena il roll e il lancio javelin per migliorare la precisione nella distribuzione. 1. Posiziona due coni a 5 metri di distanza. 2. Il portiere parte al centro, riceve il pallone e lo rotola verso il cono più lontano. 3. Dopo il roll, raccoglie il pallone e lancia un javelin verso la linea di partenza, mirando a una zona bersaglio. 4. Ripristina e ripeti 10 volte per lato.","uk":"Голкіпер практикує ролові передачі та кидки джавеліна, щоб підвищити точність розіграшу. 1. Розставте два конуси на відстані 5 метрів. 2. Воротар починає в центрі, приймає м''яч і роллює його до дальнього конуса. 3. Після ролі підбирає м''яч і виконує кидок джавеліна назад до стартової лінії, цілиться у визначену зону. 4. Скидайте позицію і повторюйте 10 разів з кожного боку."}'::jsonb,
    null,
    '{"ball"}'::text[],
    6,
    8,
    99,
    '{"en":"Accurate distribution starts attacks and relieves pressure. Keepers like Alisson and Ederson use precise throws to launch quick counters, while Manuel Neuer''s long throws break lines.","pl":"Precyzyjny wyrzut pozwala bramkarzowi szybko włączyć atak i odciążyć obronę. Łukasz Szczęsny i Wojciech Fabiański regularnie wykorzystują dokładne wyrzuty, by zaskoczyć rywali.","it":"Una buona precisione nei lanci avvia l''attacco e mantiene la squadra equilibrata. Gianluigi Buffon ha mostrato per anni l''importanza di un lancio preciso, mentre Donnarumma lo usa per transizioni rapide.","uk":"Точний розіграш дозволяє воротарю швидко переходити у атаку і зменшувати тиск. Лунін часто застосовує точні кидки, а П''ятов показав, як правильний кидок може створити моментальний контратаку."}'::jsonb,
    '{"en":["Foot placement for roll","Body alignment on javelin throw","Target accuracy","Consistent release point"],"pl":["Ustawienie stopy przy roli","Ułożenie ciała przy wyrzucie javelin","Precyzja celu","Stały punkt wypuszczenia"],"it":["Posizione del piede nel roll","Allineamento del corpo nel lancio javelin","Precisione del bersaglio","Punto di rilascio costante"],"uk":["Позиція ноги під час ролу","Вирівнювання тіла при кидку джавеліна","Точність уцільного попадання","Постійна точка випуску"]}'::jsonb,
    '{"en":"Snap your wrist on the javelin throw for a tighter, more accurate release.","pl":"Złap piłkę w ręce i wypuść ją z szybkim ruchem nadgarstka, aby zwiększyć precyzję.","it":"Scatta il polso al rilascio del javelin per una traiettoria più nitida.","uk":"Швидко відскочіть зап''ястям під час кидка, щоб забезпечити точний політ."}'::jsonb
  ),
  (
    'gk-distribution-kicking',
    'football_goalkeeper',
    'mid',
    '{"en":"Distribution Kicking Drill","pl":"Ćwiczenie Rozgrywania Kopnięć","it":"Esercizio di Rinvio","uk":"Розіграш кік"}'::jsonb,
    '{"en":"Practice accurate goal kicks and half‑volley clearances to improve your ball distribution under pressure. 1. Set up a target zone 30‑40 yards from the goal. 2. The keeper starts in the set position, receives a pass, and takes a goal kick. 3. Aim to land the ball in the target zone using a half‑volley when possible. 4. Recover quickly and repeat for 8 minutes, alternating feet. 5. Track accuracy and distance each round.","pl":"Trenuj precyzyjne wykopy i półwolne czyszczenia, aby poprawić rozgrywanie piłki pod presją. 1. Ustaw strefę docelową 30‑40 metrów od bramki. 2. Bramkarz przyjmuje podanie, ustawia pozycję i wykonuje wykop. 3. Staraj się trafić w wyznaczoną strefę, używając półwolnego, gdy to możliwe. 4. Szybko wróć do pozycji i powtarzaj przez 8 minut, zmieniając nogę. 5. Notuj celność i odległość każdego wykopu.","it":"Allena tiri lunghi e pulizie a mezza volée per migliorare la tua capacità di distribuzione. 1. Segna una zona bersaglio a 30‑40 metri dalla porta. 2. Il portiere riceve il pallone, assume la posizione e esegue il rinvio. 3. Mira a far arrivare il pallone nella zona bersaglio, preferendo una parata a mezza volée quando possibile. 4. Torna rapidamente in posizione e ripeti per 8 minuti, alternando i piedi. 5. Registra precisione e distanza ad ogni rinvio.","uk":"Тренуйте точні кидки з воротарської позиції та півволейні відчистки для кращого розподілу м''яча. 1. Позначте цільову зону на відстані 30‑40 метрів від воріт. 2. Голкіпер приймає передачу, виходить і виконує кік. 3. Намагайтеся потрапити в ціль, використовуючи півволей, коли це можливо. 4. Швидко поверніться в позицію і повторюйте протягом 8 хвилин, змінюючи ногу. 5. Записуйте точність і дальність кожного кика."}'::jsonb,
    null,
    '{"ball"}'::text[],
    8,
    8,
    99,
    '{"en":"Consistent, precise distribution starts attacks and relieves pressure. Goalkeepers like Manuel Neuer and Alisson Becker use quick, accurate kicks to turn defense into offense.","pl":"Stałe i precyzyjne rozgrywanie pozwala bramkarzowi uruchomić atak i odciążyć obronę. Szczepan Szczęsny i Łukasz Fabiański słyną z pewnych, szybka wykopów, które przełamują presję.","it":"Una distribuzione precisa avvia l''attacco e allevia la pressione. Gianluigi Buffon e Gianluigi Donnarumma mostrano come un rinvio rapido e accurato possa trasformare la difesa in occasione.","uk":"Точний розіграш дозволяє швидко переходити в атаку і знижує тиск на оборону. Лунін і Пятов відомі своїми швидкими та точними кидками, які відкривають контрнапади."}'::jsonb,
    '{"en":["Foot placement","Body balance","Ball contact point","Target accuracy","Recovery speed"],"pl":["Ustawienie stopy","Równowaga ciała","Punkt kontaktu z piłką","Celność","Szybkość powrotu"],"it":["Posizione del piede","Equilibrio del corpo","Punto di impatto","Precisione del bersaglio","Velocità di recupero"],"uk":["Позиція ноги","Баланс тіла","Точка контакту","Точність цілі","Швидкість відновлення"]}'::jsonb,
    '{"en":"Plant your non‑kicking foot beside the ball and swing through for a clean, powerful strike.","pl":"Postaw nie‑kopiącą stopę obok piłki i przeprowadź pełny zamach, aby uzyskać czysty i mocny wykop.","it":"Metti il piede non di tiro accanto al pallone e completa il movimento per un colpo pulito e potente.","uk":"Поставте незакінчувану ногу поруч з м''ячем і проведіть повний замах для чистого і сильного кика."}'::jsonb
  ),
  (
    'gk-weak-foot-kicking',
    'football_goalkeeper',
    'mid',
    '{"en":"Weak Foot Kicks","pl":"Kopnięcia słabą nogą","it":"Calci piede debole","uk":"Удари слабою ногою"}'::jsonb,
    '{"en":"Practice accurate long passes and goal kicks using your weaker foot. This builds confidence in all distribution situations. 1. Set up a line of cones 20 meters from the goal line. 2. The keeper starts in the goal, receives a ball, and must kick it with the weaker foot toward a target cone. 3. Repeat for 10 repetitions, alternating sides. 4. Focus on technique, not power, and reset after each kick.","pl":"Trenuj precyzyjne podania i wyrzuty piłki używając słabszej nogi. To zwiększa pewność w każdej sytuacji dystrybucji. 1. Ustaw szereg pachołków 20 metrów od linii bramkowej. 2. Bramkarz stoi w bramce, przyjmuje piłkę i musi wykonać kopnięcie słabą nogą w kierunku wyznaczonego pachołka. 3. Powtórz 10 razy, zmieniając stronę. 4. Skup się na technice, a nie na sile, i wracaj do pozycji po każdym kopnięciu.","it":"Allena passaggi lunghi e rilanci usando il piede più debole. Ti dà sicurezza in tutte le fasi di distribuzione. 1. Sistema dei coni a 20 metri dalla linea di porta. 2. Il portiere parte in porta, riceve il pallone e deve calciare con il piede debole verso il cono di destinazione. 3. Esegui 10 ripetizioni, alternando i lati. 4. Concentrati sulla tecnica, non sulla potenza, e ritorna in posizione dopo ogni calcio.","uk":"Тренуйте точні довгі передачі та розіграші, використовуючи слабшу ногу. Це підвищує впевненість у будь‑якій ситуації розподілу. 1. Розставте конуси на відстані 20 метрів від лінії воріт. 2. Воротар стоїть у воротах, приймає м''яч і має ударити його слабою ногою в напрямку цільового конуса. 3. Повторіть 10 разів, змінюючи сторону. 4. Сконцентруйтеся на техніці, а не на силі, і повертайтеся у позицію після кожного удару."}'::jsonb,
    null,
    '{"ball"}'::text[],
    6,
    8,
    99,
    '{"en":"A keeper who can use both feet forces opponents to think twice before pressing. Manuel Neuer and Thibaut Courtois often switch feet to open up quick counter‑attacks.","pl":"Bramkarz, który potrafi wyjść i podać piłkę słabą nogą, utrudnia przeciwnikowi presję. Szczęsny i Fabianski regularnie wykorzystują tę umiejętność, by szybciej rozpocząć atak.","it":"Un portiere che può usare entrambe le gambe costringe gli avversari a riconsiderare la pressione. Buffon e Donnarumma dimostrano spesso l''uso del piede debole per avviare contropiedi rapidi.","uk":"Воротар, який вміє грати обома ногами, ускладнює пресинг суперника. Лунін і Пятов часто використовують слабку ногу, щоб швидко розпочати контратаку."}'::jsonb,
    '{"en":["Foot placement","Body angle","Follow‑through","Accuracy","Balance"],"pl":["Ustawienie stopy","Kąt ciała","Wykonanie","Precyzja","Równowaga"],"it":["Posizione del piede","Angolo del corpo","Follow‑through","Precisione","Equilibrio"],"uk":["Позиція ноги","Кут тіла","Рух після удару","Точність","Баланс"]}'::jsonb,
    '{"en":"Imagine striking the ball as if you were passing to a teammate, not just clearing it.","pl":"Traktuj kopnięcie jak precyzyjną podanie, nie jak odległy wyrzut.","it":"Pensa al calcio come a un passaggio preciso, non solo a un allontanamento.","uk":"Уявляйте удар як точну передачу, а не лише віддалений розіграш."}'::jsonb
  ),
  (
    'gk-recovery-save',
    'football_goalkeeper',
    'high',
    '{"en":"Recovery Scramble Save","pl":"Powrót po scramble","it":"Recupero Salvataggio","uk":"Відновлення сейву"}'::jsonb,
    '{"en":"Practice quickly getting back on your feet after a dive to make a second or scramble save. 1. Start in the central goal position. 2. Have a partner shoot a low ball that forces you to dive to one side. 3. Immediately after the dive, get up, set your stance, and react to a second ball delivered within 2 seconds. 4. Focus on clean hand placement and balanced footwork. 5. Repeat alternating sides.","pl":"Ćwicz szybki powrót do pozycji po wyskoku, aby wykonać drugą lub chaotyczną parę. 1. Stań w centralnej pozycji bramkarza. 2. Partner podaje niską piłkę, zmuszając do wyjścia w jedną stronę. 3. Po lądowaniu natychmiast wstań, przyjmij pozycję i reaguj na drugą piłkę podaną w ciągu 2 sekund. 4. Zwróć uwagę na prawidłowy chwyt i stabilny wykop. 5. Powtarzaj, zmieniając strony.","it":"Allenati a rialzarti rapidamente dopo un tuffo per effettuare una seconda parata o un salvataggio caotico. 1. Posizionati al centro dei pali. 2. Un compagno lancia una palla bassa che ti costringe a un''uscita laterale. 3. Dopo la caduta, rialzati subito, assumi una buona presa e preparati per una seconda palla inviata entro 2 secondi. 4. Concentrati su una parata pulita e su un rinvio equilibrato. 5. Ripeti alternando i lati.","uk":"Тренуйте швидке підйом після падіння, щоб виконати другий або хаотичний сейв. 1. Станьте в центр воріт. 2. Партнер подає низьку м''яч, змушуючи вас вийти в бік. 3. Після падіння швидко підніміться, прийміть позицію і реагуйте на другий м''яч, поданий протягом 2 секунд. 4. Слідкуйте за чистим сейвом і стабільним кроком. 5. Повторюйте, змінюючи сторону."}'::jsonb,
    null,
    '{"ball"}'::text[],
    6,
    8,
    99,
    '{"en":"A fast recovery prevents the opposition from exploiting the open net after a missed first save. Goalkeepers like Manuel Neuer and Alisson Becker are known for their lightning‑quick second‑save reactions.","pl":"Szybki powrót pozwala bramkarzowi ograniczyć szanse przeciwnika po pierwszej nieudanej parze. Robert Szczęsny i Łukasz Fabiański wielokrotnie pokazywali, jak skutecznie wstają i wykonują kolejne obrony.","it":"Recuperare rapidamente evita che gli avversari sfruttino il vuoto lasciato da una prima parata fallita. Gianluigi Buffon e Gianluigi Donnarumma sono esempi perfetti di portieri che eccellono nei secondi salvataggi.","uk":"Швидке відновлення не дає суперникам шанс скористатися відкритою сіткою після першої помилки. Олександр Лунин і Андрій Пятов часто демонстрували вміння швидко підніматися і виконувати другий сейв."}'::jsonb,
    '{"en":["Explosive first-step up","Balanced hand placement","Quick visual reset","Accurate foot positioning"],"pl":["Eksplozywne wstawanie","Stabilny chwyt","Szybka kontrola wizualna","Precyzyjne ustawienie stóp"],"it":["Scatto esplosivo verso l''alto","Presenza stabile della mano","Ripristino visivo rapido","Posizionamento preciso dei piedi"],"uk":["Бистрий підйом","Стабільний захват","Швидке переорієнтування","Точне розташування ніг"]}'::jsonb,
    '{"en":"Treat the second ball as a fresh shot - reset your mind the moment you land.","pl":"Traktuj drugą piłkę jak nową sytuację - od razu po lądowaniu wyczyść umysł.","it":"Considera la seconda palla come un nuovo tiro - resetta la mente non appena tocchi terra.","uk":"Считайте другий м''яч новим ударом - одразу після падіння очистіть розум."}'::jsonb
  )
;
