-- 0034_sikornik_session_notes.sql
-- Add broader descriptions (note) to the SIKORNIK club-session items so the
-- plan / group page can show what each drill is, not just its name + duration.
-- i18n {pl,en,it,uk}; dollar-quoted to keep apostrophes (l', m') intact.

update public.group_session_items set note = $j${"pl":"Aktywacja z gumami mini band: krążenia bioder, wykroki i przejścia bokiem z gumą wokół kostek lub ud. Pobudza pośladki i biodra, przygotowuje mięśnie do wysiłku i ogranicza ryzyko kontuzji. Tempo spokojne — najpierw technika, potem intensywność.","en":"Mini-band activation: hip circles, lunges and lateral walks with the band around the ankles or thighs. Wakes up the glutes and hips, primes the muscles and lowers injury risk. Easy pace — technique first, intensity later.","it":"Attivazione con mini band: circonduzioni delle anche, affondi e camminate laterali con l'elastico a caviglie o cosce. Attiva glutei e anche, prepara i muscoli e riduce il rischio di infortuni. Ritmo tranquillo — prima la tecnica, poi l'intensità.","uk":"Активація з міні-гумами: обертання стегон, випади та бічні переходи з гумою на щиколотках або стегнах. Пробуджує сідниці й стегна, готує м'язи та знижує ризик травм. Спокійний темп — спершу техніка, потім інтенсивність."}$j$::jsonb where group_code='SIKORNIK' and position=0;

update public.group_session_items set note = $j${"pl":"Rondo 5 na 2 w małym kwadracie: pięciu zawodników utrzymuje piłkę, dwóch w środku próbuje ją odebrać. Ćwiczy pierwszy kontakt, podanie pod presją i grę na jeden–dwa kontakty oraz ustawienie ciała. Kto straci piłkę, wchodzi do środka.","en":"5v2 rondo in a small square: five players keep possession while two press in the middle. Trains first touch, passing under pressure, one–two-touch play and body shape. Lose the ball and you move into the middle.","it":"Torello 5 contro 2 in un quadrato piccolo: cinque giocatori mantengono il possesso mentre due recuperano al centro. Allena primo controllo, passaggio sotto pressione, gioco a uno–due tocchi e postura. Chi perde palla va al centro.","uk":"Рондо 5 на 2 у малому квадраті: п'ятеро гравців тримають м'яч, двоє в центрі намагаються його відібрати. Тренує перший дотик, пас під тиском, гру в один–два дотики та постановку корпусу. Хто втратив м'яч — іде в центр."}$j$::jsonb where group_code='SIKORNIK' and position=1;

update public.group_session_items set note = $j${"pl":"Krótki blok prewencji w stylu FIFA 11+: stabilizacja, równowaga i kontrola tułowia oraz kolan. Wzmacnia stawy i mięśnie głębokie, ogranicza urazy bezkontaktowe (kolano, kostka, mięśnie tylnej taśmy). Wykonuj powoli i dokładnie — jakość ruchu ważniejsza niż liczba powtórzeń.","en":"Short FIFA 11+ style prevention block: stability, balance and trunk and knee control. Strengthens joints and deep muscles and cuts non-contact injuries (knee, ankle, hamstrings). Go slow and precise — movement quality matters more than reps.","it":"Breve blocco di prevenzione stile FIFA 11+: stabilità, equilibrio e controllo di tronco e ginocchia. Rinforza articolazioni e muscoli profondi e riduce gli infortuni senza contatto (ginocchio, caviglia, flessori). Esegui lento e preciso — la qualità del movimento conta più delle ripetizioni.","uk":"Короткий блок профілактики у стилі FIFA 11+: стабілізація, рівновага та контроль тулуба й колін. Зміцнює суглоби та глибокі м'язи й зменшує безконтактні травми (коліно, щиколотка, задня поверхня стегна). Виконуй повільно й точно — якість руху важливіша за кількість повторень."}$j$::jsonb where group_code='SIKORNIK' and position=2;

update public.group_session_items set note = $j${"pl":"Główna część treningu: gry w małych składach (3v3/4v4) na małe bramki w formie turnieju — krótkie mecze i rotacja drużyn. Dużo kontaktu z piłką, decyzje pod presją, rywalizacja i współpraca. Zmieniaj składy oraz zasady (limit kontaktów, wielkość pola) między rundami.","en":"Main part of the session: small-sided games (3v3/4v4) on small goals in a tournament format — short matches and rotating teams. Lots of ball contact, decisions under pressure, competition and teamwork. Change teams and rules (touch limit, pitch size) between rounds.","it":"Parte principale dell'allenamento: partite a ranghi ridotti (3v3/4v4) su porte piccole in formato torneo — match brevi e squadre a rotazione. Tanti contatti con la palla, decisioni sotto pressione, competizione e collaborazione. Cambia squadre e regole (limite di tocchi, dimensioni del campo) tra i turni.","uk":"Основна частина тренування: ігри малими складами (3v3/4v4) на малі ворота у форматі турніру — короткі матчі та ротація команд. Багато контакту з м'ячем, рішення під тиском, змагання та взаємодія. Змінюй склади та правила (ліміт дотиків, розмір поля) між раундами."}$j$::jsonb where group_code='SIKORNIK' and position=3;
